// This file is automatically generated by codeviewer_cli.
// Do not edit this file.

// Copyright 2019 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:gallery/codeviewer/code_style.dart';

class CodeSegments {
  static TextSpan scaffoldDemo(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.keywordStyle, text: 'import'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(
          style: codeStyle.stringStyle,
          text: '\u0027package:flutter/material.dart\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: ';'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a'),
      TextSpan(style: codeStyle.keywordStyle, text: 'import'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(
          style: codeStyle.stringStyle,
          text: '\u0027package:gallery/codeviewer/code_segments.dart\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: ';'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a'),
      TextSpan(style: codeStyle.keywordStyle, text: 'import'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(
          style: codeStyle.stringStyle,
          text: '\u0027package:goose_ui/goose_ui.dart\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: ';'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'SizedBox'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a            height'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.numberStyle, text: '500'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a            child'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.classStyle, text: 'GScaffold'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a              appBar'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' gen'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'blue'),
      TextSpan(style: codeStyle.punctuationStyle, text: '['),
      TextSpan(style: codeStyle.numberStyle, text: '200'),
      TextSpan(style: codeStyle.punctuationStyle, text: ']!,'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.stringStyle, text: '\u0027AppBar\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a              drawer'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' gen'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'green'),
      TextSpan(style: codeStyle.punctuationStyle, text: '['),
      TextSpan(style: codeStyle.numberStyle, text: '100'),
      TextSpan(style: codeStyle.punctuationStyle, text: ']!,'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.stringStyle, text: '\u0027Drawer\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a              content'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' gen'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'grey'),
      TextSpan(style: codeStyle.punctuationStyle, text: '['),
      TextSpan(style: codeStyle.numberStyle, text: '200'),
      TextSpan(style: codeStyle.punctuationStyle, text: ']!,'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.stringStyle, text: '\u0027Content\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(
          style: codeStyle.baseStyle, text: '\u000a              systemBar'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' gen'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'amber'),
      TextSpan(style: codeStyle.punctuationStyle, text: '['),
      TextSpan(style: codeStyle.numberStyle, text: '100'),
      TextSpan(style: codeStyle.punctuationStyle, text: ']!,'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.stringStyle, text: '\u0027SystemBar\u0027'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a            '),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a          '),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }
}
